language: scala
dist: trusty
jdk: oraclejdk8

services:
  - docker

scala:
  - 2.12.8

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/node_modules

script: echo "Running tests"

jobs:
  include:
    - stage: "Run tests"
      script: scripts/run_tests.sh
    - stage: "Run cypress tests"
      script: scripts/run_cypress_tests.sh
      if: branch = TravisWithCypress
      #NOTE: Currently master branch will deploy to the development AWS environment for the purposes of Alpha
    - stage: "Deploy dev"
      script: scripts/deploy.sh dev
      if: branch = develop
    # - stage: deploytest
    #   script: scripts/deploy.sh test
    #   if: branch = test
    # - stage: deployprod
    #   script: scripts/deploy.sh latest
    #   if: branch = master