language: scala
dist: trusty
jdk: oraclejdk8

services:
  - docker

scala:
  - 2.12.8

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/node_modules

script: echo "Running tests"

jobs:
  include:
    # - stage: runtests
    #   script: scripts/run_tests.sh

    - stage: cypress
      script: scripts/run_cypress_tests.sh
      if: branch = develop
      #NOTE: Currently master branch will deploy to the development AWS environment for the purposes of Alpha
    - stage: deploy
      script: scripts/deploy.sh
      if: branch = TravisWithCypress
      # deploy:
      #   - provider: script
      #     skip_cleanup: true
      #     script: bash deploy.sh dev
      #     on:
      #       branch: TravisWithCypress
        #    branch: dev
        #- provider: script
        #  skip_cleanup: true
        #  script: bash deploy.sh test
        #  on:
        #    branch: test
        #- provider: script
        #  skip_cleanup: true
        #  script: bash deploy.sh latest
        #  on:
        #    branch: master