language: scala
dist: trusty
jdk: oraclejdk8

services:
  - docker

scala:
  - 2.12.8
jobs:
  include:
    - stage: test
      script: scripts/run_cypress_tests.sh

script:
  - npm install
  - npm run build
  - sbt dist