language: scala
dist: trusty
jdk: oraclejdk8

services:
  - docker

scala:
  - 2.12.8

script:
  - mkdir -p target/universal
  - touch target/universal/transfer-digital-records-1.0.1-SNAPSHOT.zip

deploy:
  provider: script
  script: bash deploy.sh
