language: scala
dist: trusty
jdk: oraclejdk8

services:
  - docker

scala:
  - 2.12.8

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/node_modules
jobs:
  include:
    - stage: cypress
      script: npm -i
        # - npm i
        # - npm t
        # - sbt test

    - stage: cypress
      script: 
        - npm install
        # - npm run build
        # - sbt dist
        # - docker-compose up -d
        # - npm run wait
        # - npm run cypress:ci

stages:
  - test
  - name: cypress
    if: branch = develop