language: scala
dist: trusty
jdk: oraclejdk8

scala:
  - 2.12.8

script:
  - sbt dist

before_deploy:
  - docker login $DOCKER_USERNAME $DOCKER_PASSWORD
  - docker build -t nationalarchives/prototype-play-app .
  - docker push nationalarchives/prototype-play-app
